daily

diff --git a/home/scripts/paint b/home/scripts/paint
--- a/home/scripts/paint
+++ b/home/scripts/paint
@@ -4,20 +4,32 @@
 WALLPAPER_CACHE="$HOME/.cache/wallpaper"
 [ -f "$WALLPAPER_CACHE" ] && WALLPAPER="$(cat ~/.cache/wallpaper)"
 
+# WRAP WALLUST
+# DEFAULT TO PREVIOUS WALLPAPER IN CACHE IF NO ARGUMENTS,
+# ELSE PASS ALL ARGUMENTS TO WALLUST
 if [ -z "$*" ]; then
-    wallust "$WALLPAPER" 2> /dev/null || printf "NO WALLPAPER CACHE FOUND, RELOADING ONLY\n"
+    # PICK BEST FIT COLORSCHEME IF COLORS COULD NOT BE GENERATED
+    if ! wallust "$WALLPAPER" 2> /dev/null; then
+        printf "COLORS COULD NOT BE GENERATED, THEME IS BEING USED.\n####\n"
+        THEME=$("$(dirname "$0")"/wal-theme-picker/wal-theme-picker.py -n 4 "$WALLPAPER" |
+            awk 'NR>1{print $2}' |
+            shuf -n 1)
+        wallust theme "$THEME"
+    fi
 else
     wallust "$@"
 fi
 
-if [ "$1" != "theme" ]; then
-    for ARG; do true; done
-    if [ -f "$ARG" ]; then
-        WALLPAPER="$ARG"
-        killall xwallpaper 2> /dev/null; xwallpaper --daemon --zoom "$ARG"
-        readlink -f "$WALLPAPER" > "$WALLPAPER_CACHE"
-    fi
+# CHECK IF LAST ARGUMENT IS A FILE
+for ARG; do true; done # SKIP TO LAST ARGUMENT
+if [ -f "$ARG" ]; then
+    WALLPAPER="$ARG"
+    readlink -f "$WALLPAPER" > "$WALLPAPER_CACHE"
 fi
+
+# SET WALLPAPER
+killall xwallpaper 2> /dev/null; xwallpaper --daemon --zoom "$WALLPAPER"
+
 
 # RELOAD HOOKS,
 # ARE ALWAYS RUN
